Update repo links to new repo owner
alan-turing-institute/deepsensor pull request #104
Opened 2024-03-15 16:40 UTC by davidwilby

Updating various links since the repo was transferred to a new owner. The GH ones would have redirected, but some of the links in the docs didn't so I've tried to catch them all for good measure.

2024-03-17 13:54 UTC, tom-andersson commented on CONTRIBUTING.md
> +   out [the project's roadmap](https://alan-turing-institute.github.io/deepsensorcommunity/roadmap.html).
missing fwd-slash?

2024-03-17 13:54 UTC, tom-andersson commented on CONTRIBUTING.md
> +- Check our [FAQ](https://alan-turing-institute.github.io/deepsensorcommunity/faq.html) section first.
missing fwd-slash?

2024-03-17 13:59 UTC, tom-andersson requested changes
Thanks, this is great! Happy to LGTM after:
1. Fixed the missing fwd-slash in two locations
2. Please drop the changes in the two .ipynb files and only modify the raw text where the links are stale. It is hard to review the 1,076 additions in docs/user-guide/prediction.ipynb for example. Some rationale in the contributing guide:  https://alan-turing-institute.github.io/deepsensor/community/contributing.html#contributing-to-documentation

2024-03-18 09:18 UTC, davidwilby commented on CONTRIBUTING.md
> +   out [the project's roadmap](https://alan-turing-institute.github.io/deepsensorcommunity/roadmap.html).
Good catch, thanks!

2024-03-18 10:56 UTC, merged

2024-03-18 10:58 UTC, tom-andersson commented
LGTM, thanks again @davidwilby!

@all-contributors please add @davidwilby for doc