Couple of numpy-related fixes
alan-turing-institute/deepsensor pull request #140
Opened 2024-12-13 18:31 UTC by davidwilby

## :pencil: Description
We have a few tests routinely failing at the moment for a handful of reasons mostly relating to numpy 2.

One such error is due to DeepSensor's dependency stheno not yet pinning the version of fdm which repairs some of the numpy compatibility bugs. I've raised a PR in that project here: https://github.com/wesselb/stheno/pull/27

In this PR there are a couple of corrections to alleviate test failures:
1. Use of `np.product` in some tests, this was changed in something like numpy 1.16 to `np.prod`.
2. The type of `encoder_scales` was being set to a numpy float32 with numpy 2 (possible relating to https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion) which was causing the saving and loading test to fail. I've added an `int()` but unsure if this is appropriate/ideal, though all of the tests pass locally.

## :white_check_mark: Checklist before requesting a review
(See the contributing guide for more details on these steps.)
- [x] I have installed developer dependencies with `pip install -r requirements/requirements.dev.txt` and running `pre-commit install` (or alternatively, manually running `ruff format` before commiting)

If changing or adding source code:
- [x] tests are included and are passing (run `pytest`).
- [ ] ~~documentation is included or updated as relevant, including docstrings.~~

2024-12-29 20:59 UTC, tom-andersson commented
Awesome, thanks so much for catching these niche deprecation bugs @davidwilby!

You mentioned changing encoder_scales to an int but I can't see that in this PR. Looks like the tests are passing here, so maybe it's not an issue? I see that numpy 2.2 **is** being used by the test worker.

encoder_scales has to be a float though, not an int, so we'd have to find another solution if this is an issue.

2024-12-29 21:00 UTC, tom-andersson commented on deepsensor/data/utils.py
> +    data_resolution = float(np.min([x1_res, x2_res]))
Please add a comment about why this is needed when using numpy 2 (or just state that it is needed if you don't have an explanation).

2024-12-29 21:00 UTC, tom-andersson requested changes
Awesome, thanks so much for catching these niche deprecation bugs @davidwilby!

You mentioned changing encoder_scales to an int but I can't see that in this PR. Looks like the tests are passing here, so maybe it's not an issue? I see that numpy 2.2 is being used by the test worker.

encoder_scales has to be a float though, not an int, so we'd have to find another solution if this is an issue.

2024-12-29 21:18 UTC, tom-andersson commented
@all-contributors please add @davidwilby for bug

2025-01-02 15:35 UTC, davidwilby commented
> You mentioned changing encoder_scales to an int but I can't see that in this PR. Looks like the tests are passing here, so maybe it's not an issue? I see that numpy 2.2 is being used by the test worker.

Sorry, I mistyped, I meant `float` and explained myself poorly! `model.defaults.gen_encoder_scales` calls `data.utils.compute_xarray_data_resolution` where this fix is made.

2025-01-15 06:13 UTC, merged